name: Deploy my Front-End AWS Infrastructure
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo main branch
        uses: actions/checkout@v3
        
      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Configure AWS credentials
        run: |
          export AWS_ACCESS_KEY_ID=AKIA6CY242QZNWJWFZTC
          export AWS_SECRET_ACCESS_KEY=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
          terraform init
        working-directory: ./
        
      - name: Terraform apply
        run: |
          export AWS_ACCESS_KEY_ID=AKIA6CY242QZNWJWFZTC
          export AWS_SECRET_ACCESS_KEY=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
          terraform apply -auto-approve
        working-directory: ./
