name: Deploy my Front-End AWS Infrastructure
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo main branch
        uses: actions/checkout@v3
        
      - name: Setting up terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          terraform init
        working-directory: ./
        
      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: ./
